name: gisandbox
channels:
  - conda-forge
dependencies:
  - python
  - pip



  - pip:
#     - jupyter_contrib_nbextensions
    - utm
    - matplotlib
    - matplotlib_scalebar
    - geopandas
    - shapely
    - folium
    - earthpy
    - pysal
    - textblob
    - wordcloud
    - spatialite
    - rise
    - gdal
    - fiona  
    - rasterio
    - pillow
    - ipyleaflet
    - osmnx
    - mapclassify
    - mplleaflet
      #- tensorflow
      #- mordecai
