name: gisandbox
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - rise
  - gdal
  - fiona  
  - rasterio
  - pillow
  - ipyleaflet


  - pip:
    - jupyter_contrib_nbextensions
    - utm
    - matplotlib
    - matplotlib_scalebar
    - geopandas
    - shapely
    - folium
    - earthpy
    - pysal
    - textblob
    - wordcloud
    - osmnx
    - mapclassify
    - mplleaflet
#     - spatialite
      #- tensorflow
      #- mordecai
