name: gisandbox
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - rise
  - gdal
  - fiona  
  - rasterio
  - pillow
  - ipyleaflet
  - osmnx
  - mapclassify
  - mplleaflet
  - spatialite

  - pip:
    - jupyter_contrib_nbextensions
    - utm
    - matplotlib
    - matplotlib_scalebar
    - geopandas
    - shapely
    - folium
    - earthpy
    - pysal
    - textblob
    - wordcloud
      #- tensorflow
      #- mordecai
